packages:
  - apps/*
  - packages/**/*
  - apps/desktop/layer/*
  - "!apps/mobile/native/example"
  - apps/mobile/web-app
  - "!**/example"
  - "!**/example/**"

catalog:
  "@follow-app/client-sdk": 0.3.92
  "@folo-services/ai-tools": 0.2.65
  tailwindcss-uikit-colors: 1.0.0
  typescript: 5.9.3

ignorePatchFailures: false

onlyBuiltDependencies:
  - "@firebase/util"
  - better-sqlite3
  - "@tsslint/core"
  - "@tsslint/eslint"
  - bufferutil
  - core-js
  - dtrace-provider
  - electron
  - electron-winstaller
  - esbuild
  - fast-folder-size
  - fs-xattr
  - macos-alias
  - msedge-tts
  - protobufjs
  - sharp
  - simple-git-hooks
  - utf-8-validate

overrides:
  "@electron/node-gyp": 10.2.0-electron.2
  "@floating-ui/core": 1.7.2
  "@floating-ui/dom": 1.7.2
  "@floating-ui/react": 0.27.14
  "@floating-ui/react-dom": 2.1.4
  "@react-native-menu/menu": 2.0.0
  "@types/react": 19.1.17
  drizzle-orm: 0.45.1
  global-agent>serialize-error: 7.0.1
  is-core-module: npm:@nolyfill/is-core-module@1.0.39
  isarray: npm:@nolyfill/isarray@1.0.44
  lan-network@<0.1.7: 0.1.7
  nativewind>react-native-css-interop: 0.2.1
  react: 19.1.0
  react-dom: 19.1.0
  react-native-ios-context-menu: 3.2.1
  react-native-ios-utilities: 5.2.0
  serialize-error: 2.1.0

patchedDependencies:
  "@microflash/remark-callout-directives": patches/@microflash__remark-callout-directives.patch
  "@mozilla/readability@0.6.0": patches/@mozilla__readability@0.6.0.patch
  "@pengx17/electron-forge-maker-appimage": patches/@pengx17__electron-forge-maker-appimage.patch
  daisyui@4.12.24: patches/daisyui@4.12.24.patch
  re-resizable@6.11.2: patches/re-resizable@6.11.2.patch
  react-native-sheet-transitions: patches/react-native-sheet-transitions.patch
  react-native-track-player@4.1.1: patches/react-native-track-player@4.1.1.patch
  workbox-precaching: patches/workbox-precaching.patch
